[project]
name = "people-counting-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "lap>=0.5.12",
    "sahi>=0.11.36",
    "ultralytics>=8.3.235",
]
